-- MySQL Script generated by MySQL Workbench
-- Sun 09 Sep 2018 09:17:06 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PAIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PAIS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PAIS` (
  `id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COPA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COPA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COPA` (
  `id` INT NOT NULL,
  `inicio` DATE NULL,
  `fim` DATE NULL,
  `abertura` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PESSOA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PESSOA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PESSOA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nasc` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PESSOA_PAIS1_idx` (`pais` ASC),
  CONSTRAINT `fk_PESSOA_PAIS1`
    FOREIGN KEY (`pais`)
    REFERENCES `mydb`.`PAIS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EQUIPE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `copa` INT NOT NULL,
  `pais_id` VARCHAR(10) NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `copa`),
  INDEX `fk_EQUIPE_COPA1_idx` (`copa` ASC),
  INDEX `fk_EQUIPE_PAIS1_idx` (`pais_id` ASC),
  INDEX `fk_EQUIPE_PESSOA1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_EQUIPE_COPA1`
    FOREIGN KEY (`copa`)
    REFERENCES `mydb`.`COPA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EQUIPE_PAIS1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `mydb`.`PAIS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EQUIPE_PESSOA1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`PESSOA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SEDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SEDE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SEDE` (
  `pais_id` VARCHAR(10) NOT NULL,
  `copa` INT NOT NULL,
  INDEX `fk_PAIS_has_COPA_COPA2_idx` (`copa` ASC),
  INDEX `fk_PAIS_has_COPA_PAIS1_idx` (`pais_id` ASC),
  PRIMARY KEY (`pais_id`, `copa`),
  CONSTRAINT `fk_PAIS_has_COPA_PAIS1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `mydb`.`PAIS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAIS_has_COPA_COPA2`
    FOREIGN KEY (`copa`)
    REFERENCES `mydb`.`COPA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JOGO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JOGO` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estadio` VARCHAR(45) NOT NULL,
  `eq1` INT NOT NULL,
  `eq2` INT NOT NULL,
  `gol1` INT NULL,
  `gol2` INT NULL,
  `COPA_id` INT NOT NULL,
  INDEX `fk_JOGO_EQUIPE1_idx` (`eq1` ASC),
  INDEX `fk_JOGO_EQUIPE2_idx` (`eq2` ASC),
  PRIMARY KEY (`numero`, `COPA_id`),
  INDEX `fk_JOGO_COPA1_idx` (`COPA_id` ASC),
  CONSTRAINT `fk_JOGO_EQUIPE1`
    FOREIGN KEY (`eq1`)
    REFERENCES `mydb`.`EQUIPE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JOGO_EQUIPE2`
    FOREIGN KEY (`eq2`)
    REFERENCES `mydb`.`EQUIPE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JOGO_COPA1`
    FOREIGN KEY (`COPA_id`)
    REFERENCES `mydb`.`COPA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOGADORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JOGADORES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JOGADORES` (
  `pessoa_id` INT NOT NULL,
  `equipe_id` INT NOT NULL,
  INDEX `fk_PESSOA_has_EQUIPE_EQUIPE1_idx` (`equipe_id` ASC),
  INDEX `fk_PESSOA_has_EQUIPE_PESSOA1_idx` (`pessoa_id` ASC),
  PRIMARY KEY (`pessoa_id`, `equipe_id`),
  CONSTRAINT `fk_PESSOA_has_EQUIPE_PESSOA1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`PESSOA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESSOA_has_EQUIPE_EQUIPE1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `mydb`.`EQUIPE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
