# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      # POSTGRES_USER: root
    volumes:
      # - $PWD/all:/etc
      - $PWD/:/home/bda
    ports:
      - 8090:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080