-- MySQL Script generated by MySQL Workbench
-- Sun 09 Sep 2018 09:17:06 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward
-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS DEFAULTCHARACTER SET utf8 ;

create database mydb;
-- -----------------------------------------------------
-- Table PAIS
-- -----------------------------------------------------

\c mydb;

-- DROP TABLE IF EXISTS PAIS ;

CREATE TABLE IF NOT EXISTS PAIS (
  id VARCHAR(10) NOT NULL,
  nome VARCHAR(45) NOT NULL,
  PRIMARY KEY (id));
  CREATE UNIQUE INDEX on PAIS(nome);


-- -----------------------------------------------------
-- Table COPA
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS COPA ;

CREATE TABLE IF NOT EXISTS COPA (
  id INT NOT NULL,
  inicio DATE NULL,
  fim DATE NULL,
  abertura VARCHAR(45) NULL,
  PRIMARY KEY (id));



-- -----------------------------------------------------
-- Table PESSOA
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS PESSOA ;

CREATE TABLE IF NOT EXISTS PESSOA (
  id SERIAL,
  pais VARCHAR(10) NOT NULL,
  nome VARCHAR(45) NOT NULL,
  nasc DATE NULL,
  PRIMARY KEY (id),
  
  CONSTRAINT fk_PESSOA_PAIS1
    FOREIGN KEY (pais)
    REFERENCES PAIS (id));


-- -----------------------------------------------------
-- Table EQUIPE
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS EQUIPE ;

CREATE TABLE IF NOT EXISTS EQUIPE (
  id SERIAL,
  copa INT NOT NULL,
  pais_id VARCHAR(10) NOT NULL,
  pessoa_id INT NOT NULL,
  PRIMARY KEY (id, copa),
  
  
  
  CONSTRAINT fk_EQUIPE_COPA1
    FOREIGN KEY (copa)
    REFERENCES COPA (id),
  CONSTRAINT fk_EQUIPE_PAIS1
    FOREIGN KEY (pais_id)
    REFERENCES PAIS (id),
  CONSTRAINT fk_EQUIPE_PESSOA1
    FOREIGN KEY (pessoa_id)
    REFERENCES PESSOA (id));
CREATE UNIQUE INDEX on EQUIPE(id);

-- -----------------------------------------------------
-- Table SEDE
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS SEDE ;

CREATE TABLE IF NOT EXISTS SEDE (
  pais_id VARCHAR(10) NOT NULL,
  copa INT NOT NULL,
  
  
  PRIMARY KEY (pais_id, copa),
  CONSTRAINT fk_PAIS_has_COPA_PAIS1
    FOREIGN KEY (pais_id)
    REFERENCES PAIS (id),
  CONSTRAINT fk_PAIS_has_COPA_COPA2
    FOREIGN KEY (copa)
    REFERENCES COPA (id));


-- -----------------------------------------------------
-- Table JOGO
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS JOGO ;

CREATE TABLE IF NOT EXISTS JOGO (
  numero SERIAL,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  estadio VARCHAR(45) NOT NULL,
  eq1 INT NOT NULL,
  eq2 INT NOT NULL,
  gol1 INT NULL,
  gol2 INT NULL,
  COPA_id INT NOT NULL,
  
  
  PRIMARY KEY (numero, COPA_id),
  
  CONSTRAINT fk_JOGO_EQUIPE1
    FOREIGN KEY (eq1)
    REFERENCES EQUIPE (id),
  CONSTRAINT fk_JOGO_EQUIPE2
    FOREIGN KEY (eq2)
    REFERENCES EQUIPE (id),
  CONSTRAINT fk_JOGO_COPA1
    FOREIGN KEY (COPA_id)
    REFERENCES COPA (id));


-- -----------------------------------------------------
-- Table JOGADORES
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS JOGADORES ;

CREATE TABLE IF NOT EXISTS JOGADORES (
  pessoa_id INT NOT NULL,
  equipe_id INT NOT NULL,
  
  
  PRIMARY KEY (pessoa_id, equipe_id),
  CONSTRAINT fk_PESSOA_has_EQUIPE_PESSOA1
    FOREIGN KEY (pessoa_id)
    REFERENCES PESSOA (id),
  CONSTRAINT fk_PESSOA_has_EQUIPE_EQUIPE1
    FOREIGN KEY (equipe_id)
    REFERENCES EQUIPE (id));

-- source createView.sql;  -- Manualmente inserido xD. Para facilitar as queries

-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
